from app.schemas.auth import *
from app.schemas.zone import *
from app.schemas.vehicle_type import *
from app.schemas.parking_spot import *
from app.schemas.vehicle import *
from app.schemas.pricing import *
from app.schemas.monthly_pass import *
from app.schemas.parking_session import *
from app.schemas.stats import *
from app.schemas.ai import *
